# Generated by Django 4.2.7 on 2023-11-27 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id_espaco', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('num_telefone', models.CharField(max_length=50)),
                ('siape', models.CharField(max_length=50)),
                ('id_espaco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogoApp.espaco')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('tombo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('id_espaco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogoApp.espaco')),
            ],
        ),
    ]
